# Generated by Django 2.2.4 on 2019-08-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190822_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chice_text',
            new_name='choice_text',
        ),
    ]
